### ISSUE TITLE
Incomplete sentence in manual about REDO

### ISSUE THREAD

**Issue by auraes** [daad-adventure-writer/daad#1]
Hello,
in the documentation DAAD_Manual_1991.pdf, the sentence about REDO doesn't seem to be finished:
REDO
Will restart the currently executing table, allowing

**Comment by ByteProject** [comment]
Hi @auraes, 
thanks for pointing that out. Yes, the historical documents are not perfect unfortunately. We agreed internally that - due to the historic nature of the documentation - we won't modify it. 

REDO restarts the currently executing table, allowing you to implement a loop logic in your code.
